### ISSUE TITLE
gk61 fnbase layer

### ISSUE THREAD

**Issue by DA-RAE** [pixeltris/GK6X#52] opened 2020-07-03 14:39 UTC
I can remap base layer and other layers. But I can't remap fnbase layer.(
This makes no reason to use this program instead of using the original program.)

Is there any way to remap the fnbase layer in gk61?

**Comment by pixeltris** [comment] 2020-07-03 21:16
Yea I would totally recommend using the official software. I made this to find out if there were any hidden features available on the keyboard. The official software doesn't allow you to re-map the base layer (though I think some variants of it do) which is one of the minor benefits of this tool.

The fn key set on the base layer cannot be mapped, this is a firmware limitation. Modifications to the firmware would be required to get this working. See the work done on disassembling the official firmware at https://github.com/wgwoods/gk64-python/tree/master/disasm

**Comment by KarBoy2314PL** [comment] 2020-07-08 14:43
duplicate of #37

**Comment by samiyuru** [comment] 2020-10-09 01:05
Is there any possibility of flashing a patched version of the firmware?

**Comment by pixeltris** [comment] 2020-10-09 01:32
So that FnBase could be modified? I'm not sure if it would be super straight forward.

Each board is going to have its own firmware so you'll need a way to extract the original firmware in the first place (I think GK64 is the only board where firmware could be downloaded, for other boards you would need to modify your board somehow to dump the memory).

Once you have the original firmware you need to traverse the disassembly (some work has been done on this already https://github.com/wgwoods/gk64-python/blob/master/disasm/BBD8.disasm) and find where it deals with layers. It could be that the firmware doesn't have any pre-allocated space already so its probably not a simple conditional jump change.

**Comment by h3oCharles** [comment] 2020-10-10 11:53
> Is there any possibility of flashing a patched version of the firmware?

that's easier said than done, yea

also, separate issue for this plz...?

**Closed** 2021-01-16 13:45 UTC
